FROM node:20-alpine

LABEL maintainer="Arian Esmkhani"
LABEL version="1.0"

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 5009
CMD ["pnpm", "start"]
